name: GVM Compress
on:
  workflow_call:

jobs:
  web-compress:
    name: 🗜️Compress
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2
        with:

      - name: 〽️ Minify
        uses: anthonyftwang/minify-action@v1.0.1

      - name: 📂 Sync files
      - uses: stefanzweifel/git-auto-commit-action@v4
  
