name: GVM Deploy
on:
  workflow_call:
    inputs:
      directory:
        required: true
        type: string
      domain:
        required: true
        type: string
    secrets:
      ftp:
        required: true
        
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.1
      with:
        server: ${{inputs.domain}}
        username: gvm@${{inputs.domain}}
        password: ${{secrets.ftp}}
        server-dir: ${{inputs.domain}}${{inputs.directory}}
        protocol: ftps
